# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{sixhour}
  s.version = "0.2.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Tom Wilson"]
  s.date = %q{2010-02-14}
  s.description = %q{gem install sixhour}
  s.email = %q{tom@jackhq.com}
  s.files = [
    "Gemfile",
     "app.rb",
     "config.ru",
     "lib/swat.rb",
     "public/images/sixhour.png",
     "public/javascripts/jquery-1.4.1.min.js",
     "public/stylesheets/960.css",
     "public/stylesheets/app.css",
     "public/stylesheets/reset.css",
     "public/stylesheets/text.css",
     "readme.md",
     "spec/app_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "views/index.haml",
     "views/layout.haml"
  ]
  s.homepage = %q{http://github.com/twilson63/sixhour}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Simple Web Application Template}
  s.test_files = [
    "spec/app_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<bundler>, ["= 0.9.5"])
      s.add_runtime_dependency(%q<sinatra>, ["= 0.9.4"])
      s.add_runtime_dependency(%q<haml>, [">= 2.2.17"])
    else
      s.add_dependency(%q<bundler>, ["= 0.9.5"])
      s.add_dependency(%q<sinatra>, ["= 0.9.4"])
      s.add_dependency(%q<haml>, [">= 2.2.17"])
    end
  else
    s.add_dependency(%q<bundler>, ["= 0.9.5"])
    s.add_dependency(%q<sinatra>, ["= 0.9.4"])
    s.add_dependency(%q<haml>, [">= 2.2.17"])
  end
end

